### ISSUE TITLE
API, when searching multiple organisms, OR search is not commutative 

### ISSUE THREAD

**Issue by marco-brandizi** [EBIBioStudies/biostudies-backend-services#901]
Hi all, 

I'm trying to use the BioStudies API in this [BioHackathon project](https://github.com/elixir-europe/biohackathon-projects-2024/blob/main/24.md), I'm seeing weird results from the /search API.

This call:

`https://www.ebi.ac.uk/biostudies/api/v1/ArrayExpress/search?organism="Triticum aestivum" OR "Arabidopsis thaliana"&pageSize=100&page=1&link_type=gxa`

returns totalHits = 597

If I swap the terms in organisms:

`https://www.ebi.ac.uk/biostudies/api/v1/ArrayExpress/search?organism="Arabidopsis thaliana" OR "Triticum aestivum"&pageSize=100&page=1&link_type=gxa`

I get totalHits = 592

I've tried to URL-encode the organism parameter and I got the same results.

I would expect the search to be exact on the organisms (ie, exact matches on the organism field) and that the result is the union of each specified specie. I've thought that maybe the results are scored and only the top hits are returned, but since `isTotalHitsExact` is true, it shouldn't have such a behaviour.

Is it a bug or am I doing something wrong?

**Comment by awaisathar** [comment]
Thanks @marco-brandizi, the [REST interface for BioStudies](https://github.com/EBIBioStudies/ribs) supports the [Lucene Query Paraser syntax](https://lucene.apache.org/core/10_0_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package.description) so you might want to add the field name to both strings. Something like [(organism:"Triticum aestivum" OR organism:"Arabidopsis thaliana") AND link_type:gxa](https://www.ebi.ac.uk/biostudies/api/v1/search?query=(organism:%22Triticum%20aestivum%22%20OR%20organism:%22Arabidopsis%20thaliana%22)%20AND%20link_type:gxa) seems to work. Please drop us an mail if the behaviour is not expected. We'll try to add this in the help docs.

**Comment by marco-brandizi** [comment]
Hi @awaisathar thank you for your reply. Indeed, this works as expected:

`https://www.ebi.ac.uk/biostudies/api/v1/ArrayExpress/search?query=organism:"Arabidopsis Thaliana" OR organism:"Triticum Aestivum"&pageSize=100&page=1&link_type=gxa`

so, I understand several (all?) parameters can be given either as URL parameters or as fields in a Lucene query.
